language: go

go: 
  - 1.9.x
  - 1.10.x
  - 1.11.x

install:
  - go get github.com/jinzhu/gorm
  - go get github.com/go-sql-driver/mysql
  - go get gopkg.in/yaml.v2

script:
  - make lint
  - make test
  - make build